/**
 * Compile `theme/tailwind.css` into `theme/css.ts`.
 *
 * The stylesheet ships as a TypeScript string rather than a `.css` file
 * because a kit component is bundled by `esbuild --bundle` with no loader
 * configuration (see `@open-competition-kit/sdk`'s `makeComponent`). A string
 * is the one form the bundler will carry without being taught anything.
 */
import { $ } from "bun";

const here = new URL(".", import.meta.url).pathname;
const input = `${here}tailwind.css`;
const output = `${here}css.ts`;

const compiled = await $`bunx @tailwindcss/cli --input ${input} --minify`.text();

const banner = [
  "// Generated by `bun run build:css` from `theme/tailwind.css`.",
  "// Edit that file, not this one.",
  "",
  "export const css = String.raw`",
].join("\n");

// String.raw leaves backslashes alone, so only the delimiters and `${` need
// escaping for the value to survive as a template literal.
const escaped = compiled.replaceAll("`", "\\`").replaceAll("${", "$\\{");

await Bun.write(output, `${banner}${escaped}\`;\n`);

console.log(`Wrote ${output} (${(compiled.length / 1024).toFixed(1)} KB)`);
