/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as CompetitionsIndexRouteImport } from './routes/competitions/index'
import { Route as DashboardCompetitionIdRouteRouteImport } from './routes/dashboard/$competitionId/route'
import { Route as CompetitionsIdRouteRouteImport } from './routes/competitions/$id/route'
import { Route as CompetitionsIdIndexRouteImport } from './routes/competitions/$id/index'
import { Route as DashboardCompetitionIdOverviewIndexRouteImport } from './routes/dashboard/$competitionId/overview/index'
import { Route as DashboardCompetitionIdConfigureIndexRouteImport } from './routes/dashboard/$competitionId/configure/index'
import { Route as CompetitionsIdTracksIndexRouteImport } from './routes/competitions/$id/tracks/index'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const CompetitionsIndexRoute = CompetitionsIndexRouteImport.update({
  id: '/competitions/',
  path: '/competitions/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCompetitionIdRouteRoute =
  DashboardCompetitionIdRouteRouteImport.update({
    id: '/$competitionId',
    path: '/$competitionId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const CompetitionsIdRouteRoute = CompetitionsIdRouteRouteImport.update({
  id: '/competitions/$id',
  path: '/competitions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsIdIndexRoute = CompetitionsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompetitionsIdRouteRoute,
} as any)
const DashboardCompetitionIdOverviewIndexRoute =
  DashboardCompetitionIdOverviewIndexRouteImport.update({
    id: '/overview/',
    path: '/overview/',
    getParentRoute: () => DashboardCompetitionIdRouteRoute,
  } as any)
const DashboardCompetitionIdConfigureIndexRoute =
  DashboardCompetitionIdConfigureIndexRouteImport.update({
    id: '/configure/',
    path: '/configure/',
    getParentRoute: () => DashboardCompetitionIdRouteRoute,
  } as any)
const CompetitionsIdTracksIndexRoute =
  CompetitionsIdTracksIndexRouteImport.update({
    id: '/tracks/',
    path: '/tracks/',
    getParentRoute: () => CompetitionsIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/competitions/$id': typeof CompetitionsIdRouteRouteWithChildren
  '/dashboard/$competitionId': typeof DashboardCompetitionIdRouteRouteWithChildren
  '/competitions': typeof CompetitionsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/competitions/$id/': typeof CompetitionsIdIndexRoute
  '/competitions/$id/tracks': typeof CompetitionsIdTracksIndexRoute
  '/dashboard/$competitionId/configure': typeof DashboardCompetitionIdConfigureIndexRoute
  '/dashboard/$competitionId/overview': typeof DashboardCompetitionIdOverviewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/$competitionId': typeof DashboardCompetitionIdRouteRouteWithChildren
  '/competitions': typeof CompetitionsIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/competitions/$id': typeof CompetitionsIdIndexRoute
  '/competitions/$id/tracks': typeof CompetitionsIdTracksIndexRoute
  '/dashboard/$competitionId/configure': typeof DashboardCompetitionIdConfigureIndexRoute
  '/dashboard/$competitionId/overview': typeof DashboardCompetitionIdOverviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/competitions/$id': typeof CompetitionsIdRouteRouteWithChildren
  '/dashboard/$competitionId': typeof DashboardCompetitionIdRouteRouteWithChildren
  '/competitions/': typeof CompetitionsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/competitions/$id/': typeof CompetitionsIdIndexRoute
  '/competitions/$id/tracks/': typeof CompetitionsIdTracksIndexRoute
  '/dashboard/$competitionId/configure/': typeof DashboardCompetitionIdConfigureIndexRoute
  '/dashboard/$competitionId/overview/': typeof DashboardCompetitionIdOverviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/competitions/$id'
    | '/dashboard/$competitionId'
    | '/competitions'
    | '/dashboard/'
    | '/competitions/$id/'
    | '/competitions/$id/tracks'
    | '/dashboard/$competitionId/configure'
    | '/dashboard/$competitionId/overview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/$competitionId'
    | '/competitions'
    | '/dashboard'
    | '/competitions/$id'
    | '/competitions/$id/tracks'
    | '/dashboard/$competitionId/configure'
    | '/dashboard/$competitionId/overview'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/competitions/$id'
    | '/dashboard/$competitionId'
    | '/competitions/'
    | '/dashboard/'
    | '/competitions/$id/'
    | '/competitions/$id/tracks/'
    | '/dashboard/$competitionId/configure/'
    | '/dashboard/$competitionId/overview/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  CompetitionsIdRouteRoute: typeof CompetitionsIdRouteRouteWithChildren
  CompetitionsIndexRoute: typeof CompetitionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/competitions/': {
      id: '/competitions/'
      path: '/competitions'
      fullPath: '/competitions'
      preLoaderRoute: typeof CompetitionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$competitionId': {
      id: '/dashboard/$competitionId'
      path: '/$competitionId'
      fullPath: '/dashboard/$competitionId'
      preLoaderRoute: typeof DashboardCompetitionIdRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/competitions/$id': {
      id: '/competitions/$id'
      path: '/competitions/$id'
      fullPath: '/competitions/$id'
      preLoaderRoute: typeof CompetitionsIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions/$id/': {
      id: '/competitions/$id/'
      path: '/'
      fullPath: '/competitions/$id/'
      preLoaderRoute: typeof CompetitionsIdIndexRouteImport
      parentRoute: typeof CompetitionsIdRouteRoute
    }
    '/dashboard/$competitionId/overview/': {
      id: '/dashboard/$competitionId/overview/'
      path: '/overview'
      fullPath: '/dashboard/$competitionId/overview'
      preLoaderRoute: typeof DashboardCompetitionIdOverviewIndexRouteImport
      parentRoute: typeof DashboardCompetitionIdRouteRoute
    }
    '/dashboard/$competitionId/configure/': {
      id: '/dashboard/$competitionId/configure/'
      path: '/configure'
      fullPath: '/dashboard/$competitionId/configure'
      preLoaderRoute: typeof DashboardCompetitionIdConfigureIndexRouteImport
      parentRoute: typeof DashboardCompetitionIdRouteRoute
    }
    '/competitions/$id/tracks/': {
      id: '/competitions/$id/tracks/'
      path: '/tracks'
      fullPath: '/competitions/$id/tracks'
      preLoaderRoute: typeof CompetitionsIdTracksIndexRouteImport
      parentRoute: typeof CompetitionsIdRouteRoute
    }
  }
}

interface DashboardCompetitionIdRouteRouteChildren {
  DashboardCompetitionIdConfigureIndexRoute: typeof DashboardCompetitionIdConfigureIndexRoute
  DashboardCompetitionIdOverviewIndexRoute: typeof DashboardCompetitionIdOverviewIndexRoute
}

const DashboardCompetitionIdRouteRouteChildren: DashboardCompetitionIdRouteRouteChildren =
  {
    DashboardCompetitionIdConfigureIndexRoute:
      DashboardCompetitionIdConfigureIndexRoute,
    DashboardCompetitionIdOverviewIndexRoute:
      DashboardCompetitionIdOverviewIndexRoute,
  }

const DashboardCompetitionIdRouteRouteWithChildren =
  DashboardCompetitionIdRouteRoute._addFileChildren(
    DashboardCompetitionIdRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardCompetitionIdRouteRoute: typeof DashboardCompetitionIdRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardCompetitionIdRouteRoute:
    DashboardCompetitionIdRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface CompetitionsIdRouteRouteChildren {
  CompetitionsIdIndexRoute: typeof CompetitionsIdIndexRoute
  CompetitionsIdTracksIndexRoute: typeof CompetitionsIdTracksIndexRoute
}

const CompetitionsIdRouteRouteChildren: CompetitionsIdRouteRouteChildren = {
  CompetitionsIdIndexRoute: CompetitionsIdIndexRoute,
  CompetitionsIdTracksIndexRoute: CompetitionsIdTracksIndexRoute,
}

const CompetitionsIdRouteRouteWithChildren =
  CompetitionsIdRouteRoute._addFileChildren(CompetitionsIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  CompetitionsIdRouteRoute: CompetitionsIdRouteRouteWithChildren,
  CompetitionsIndexRoute: CompetitionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
