/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MeRouteRouteImport } from './routes/me/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignInIndexRouteImport } from './routes/sign-in/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as MeIndexRouteImport } from './routes/me/index'
import { Route as LeaderboardsIndexRouteImport } from './routes/leaderboards/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as CompetitionsIndexRouteImport } from './routes/competitions/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as MeSettingsRouteImport } from './routes/me/settings'
import { Route as MeEnrolmentsRouteImport } from './routes/me/enrolments'
import { Route as DashboardCompetitionIdRouteRouteImport } from './routes/dashboard/$competitionId/route'
import { Route as CompetitionsIdRouteRouteImport } from './routes/competitions/$id/route'
import { Route as MeSubmissionsIndexRouteImport } from './routes/me/submissions/index'
import { Route as CompetitionsIdIndexRouteImport } from './routes/competitions/$id/index'
import { Route as MeSubmissionsSubmissionIdRouteImport } from './routes/me/submissions/$submissionId'
import { Route as CompetitionsIdRulesRouteImport } from './routes/competitions/$id/rules'
import { Route as CompetitionsIdEnrolRouteImport } from './routes/competitions/$id/enrol'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardCompetitionIdOverviewIndexRouteImport } from './routes/dashboard/$competitionId/overview/index'
import { Route as DashboardCompetitionIdConfigureIndexRouteImport } from './routes/dashboard/$competitionId/configure/index'
import { Route as CompetitionsIdTracksIndexRouteImport } from './routes/competitions/$id/tracks/index'
import { Route as CompetitionsIdSubmissionsIndexRouteImport } from './routes/competitions/$id/submissions/index'
import { Route as CompetitionsIdTracksTrackIdRouteImport } from './routes/competitions/$id/tracks/$trackId'
import { Route as CompetitionsIdSubmissionsNewRouteImport } from './routes/competitions/$id/submissions/new'

const MeRouteRoute = MeRouteRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInIndexRoute = SignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeIndexRoute = MeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MeRouteRoute,
} as any)
const LeaderboardsIndexRoute = LeaderboardsIndexRouteImport.update({
  id: '/leaderboards/',
  path: '/leaderboards/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const CompetitionsIndexRoute = CompetitionsIndexRouteImport.update({
  id: '/competitions/',
  path: '/competitions/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeSettingsRoute = MeSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MeRouteRoute,
} as any)
const MeEnrolmentsRoute = MeEnrolmentsRouteImport.update({
  id: '/enrolments',
  path: '/enrolments',
  getParentRoute: () => MeRouteRoute,
} as any)
const DashboardCompetitionIdRouteRoute =
  DashboardCompetitionIdRouteRouteImport.update({
    id: '/$competitionId',
    path: '/$competitionId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const CompetitionsIdRouteRoute = CompetitionsIdRouteRouteImport.update({
  id: '/competitions/$id',
  path: '/competitions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MeSubmissionsIndexRoute = MeSubmissionsIndexRouteImport.update({
  id: '/submissions/',
  path: '/submissions/',
  getParentRoute: () => MeRouteRoute,
} as any)
const CompetitionsIdIndexRoute = CompetitionsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompetitionsIdRouteRoute,
} as any)
const MeSubmissionsSubmissionIdRoute =
  MeSubmissionsSubmissionIdRouteImport.update({
    id: '/submissions/$submissionId',
    path: '/submissions/$submissionId',
    getParentRoute: () => MeRouteRoute,
  } as any)
const CompetitionsIdRulesRoute = CompetitionsIdRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => CompetitionsIdRouteRoute,
} as any)
const CompetitionsIdEnrolRoute = CompetitionsIdEnrolRouteImport.update({
  id: '/enrol',
  path: '/enrol',
  getParentRoute: () => CompetitionsIdRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCompetitionIdOverviewIndexRoute =
  DashboardCompetitionIdOverviewIndexRouteImport.update({
    id: '/overview/',
    path: '/overview/',
    getParentRoute: () => DashboardCompetitionIdRouteRoute,
  } as any)
const DashboardCompetitionIdConfigureIndexRoute =
  DashboardCompetitionIdConfigureIndexRouteImport.update({
    id: '/configure/',
    path: '/configure/',
    getParentRoute: () => DashboardCompetitionIdRouteRoute,
  } as any)
const CompetitionsIdTracksIndexRoute =
  CompetitionsIdTracksIndexRouteImport.update({
    id: '/tracks/',
    path: '/tracks/',
    getParentRoute: () => CompetitionsIdRouteRoute,
  } as any)
const CompetitionsIdSubmissionsIndexRoute =
  CompetitionsIdSubmissionsIndexRouteImport.update({
    id: '/submissions/',
    path: '/submissions/',
    getParentRoute: () => CompetitionsIdRouteRoute,
  } as any)
const CompetitionsIdTracksTrackIdRoute =
  CompetitionsIdTracksTrackIdRouteImport.update({
    id: '/tracks/$trackId',
    path: '/tracks/$trackId',
    getParentRoute: () => CompetitionsIdRouteRoute,
  } as any)
const CompetitionsIdSubmissionsNewRoute =
  CompetitionsIdSubmissionsNewRouteImport.update({
    id: '/submissions/new',
    path: '/submissions/new',
    getParentRoute: () => CompetitionsIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/me': typeof MeRouteRouteWithChildren
  '/competitions/$id': typeof CompetitionsIdRouteRouteWithChildren
  '/dashboard/$competitionId': typeof DashboardCompetitionIdRouteRouteWithChildren
  '/me/enrolments': typeof MeEnrolmentsRoute
  '/me/settings': typeof MeSettingsRoute
  '/about/': typeof AboutIndexRoute
  '/competitions/': typeof CompetitionsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/leaderboards/': typeof LeaderboardsIndexRoute
  '/me/': typeof MeIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/competitions/$id/enrol': typeof CompetitionsIdEnrolRoute
  '/competitions/$id/rules': typeof CompetitionsIdRulesRoute
  '/me/submissions/$submissionId': typeof MeSubmissionsSubmissionIdRoute
  '/competitions/$id/': typeof CompetitionsIdIndexRoute
  '/me/submissions/': typeof MeSubmissionsIndexRoute
  '/competitions/$id/submissions/new': typeof CompetitionsIdSubmissionsNewRoute
  '/competitions/$id/tracks/$trackId': typeof CompetitionsIdTracksTrackIdRoute
  '/competitions/$id/submissions/': typeof CompetitionsIdSubmissionsIndexRoute
  '/competitions/$id/tracks/': typeof CompetitionsIdTracksIndexRoute
  '/dashboard/$competitionId/configure/': typeof DashboardCompetitionIdConfigureIndexRoute
  '/dashboard/$competitionId/overview/': typeof DashboardCompetitionIdOverviewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/$competitionId': typeof DashboardCompetitionIdRouteRouteWithChildren
  '/me/enrolments': typeof MeEnrolmentsRoute
  '/me/settings': typeof MeSettingsRoute
  '/about': typeof AboutIndexRoute
  '/competitions': typeof CompetitionsIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/leaderboards': typeof LeaderboardsIndexRoute
  '/me': typeof MeIndexRoute
  '/register': typeof RegisterIndexRoute
  '/sign-in': typeof SignInIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/competitions/$id/enrol': typeof CompetitionsIdEnrolRoute
  '/competitions/$id/rules': typeof CompetitionsIdRulesRoute
  '/me/submissions/$submissionId': typeof MeSubmissionsSubmissionIdRoute
  '/competitions/$id': typeof CompetitionsIdIndexRoute
  '/me/submissions': typeof MeSubmissionsIndexRoute
  '/competitions/$id/submissions/new': typeof CompetitionsIdSubmissionsNewRoute
  '/competitions/$id/tracks/$trackId': typeof CompetitionsIdTracksTrackIdRoute
  '/competitions/$id/submissions': typeof CompetitionsIdSubmissionsIndexRoute
  '/competitions/$id/tracks': typeof CompetitionsIdTracksIndexRoute
  '/dashboard/$competitionId/configure': typeof DashboardCompetitionIdConfigureIndexRoute
  '/dashboard/$competitionId/overview': typeof DashboardCompetitionIdOverviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/me': typeof MeRouteRouteWithChildren
  '/competitions/$id': typeof CompetitionsIdRouteRouteWithChildren
  '/dashboard/$competitionId': typeof DashboardCompetitionIdRouteRouteWithChildren
  '/me/enrolments': typeof MeEnrolmentsRoute
  '/me/settings': typeof MeSettingsRoute
  '/about/': typeof AboutIndexRoute
  '/competitions/': typeof CompetitionsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/leaderboards/': typeof LeaderboardsIndexRoute
  '/me/': typeof MeIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/competitions/$id/enrol': typeof CompetitionsIdEnrolRoute
  '/competitions/$id/rules': typeof CompetitionsIdRulesRoute
  '/me/submissions/$submissionId': typeof MeSubmissionsSubmissionIdRoute
  '/competitions/$id/': typeof CompetitionsIdIndexRoute
  '/me/submissions/': typeof MeSubmissionsIndexRoute
  '/competitions/$id/submissions/new': typeof CompetitionsIdSubmissionsNewRoute
  '/competitions/$id/tracks/$trackId': typeof CompetitionsIdTracksTrackIdRoute
  '/competitions/$id/submissions/': typeof CompetitionsIdSubmissionsIndexRoute
  '/competitions/$id/tracks/': typeof CompetitionsIdTracksIndexRoute
  '/dashboard/$competitionId/configure/': typeof DashboardCompetitionIdConfigureIndexRoute
  '/dashboard/$competitionId/overview/': typeof DashboardCompetitionIdOverviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/me'
    | '/competitions/$id'
    | '/dashboard/$competitionId'
    | '/me/enrolments'
    | '/me/settings'
    | '/about/'
    | '/competitions/'
    | '/dashboard/'
    | '/leaderboards/'
    | '/me/'
    | '/register/'
    | '/sign-in/'
    | '/api/auth/$'
    | '/competitions/$id/enrol'
    | '/competitions/$id/rules'
    | '/me/submissions/$submissionId'
    | '/competitions/$id/'
    | '/me/submissions/'
    | '/competitions/$id/submissions/new'
    | '/competitions/$id/tracks/$trackId'
    | '/competitions/$id/submissions/'
    | '/competitions/$id/tracks/'
    | '/dashboard/$competitionId/configure/'
    | '/dashboard/$competitionId/overview/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/$competitionId'
    | '/me/enrolments'
    | '/me/settings'
    | '/about'
    | '/competitions'
    | '/dashboard'
    | '/leaderboards'
    | '/me'
    | '/register'
    | '/sign-in'
    | '/api/auth/$'
    | '/competitions/$id/enrol'
    | '/competitions/$id/rules'
    | '/me/submissions/$submissionId'
    | '/competitions/$id'
    | '/me/submissions'
    | '/competitions/$id/submissions/new'
    | '/competitions/$id/tracks/$trackId'
    | '/competitions/$id/submissions'
    | '/competitions/$id/tracks'
    | '/dashboard/$competitionId/configure'
    | '/dashboard/$competitionId/overview'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/me'
    | '/competitions/$id'
    | '/dashboard/$competitionId'
    | '/me/enrolments'
    | '/me/settings'
    | '/about/'
    | '/competitions/'
    | '/dashboard/'
    | '/leaderboards/'
    | '/me/'
    | '/register/'
    | '/sign-in/'
    | '/api/auth/$'
    | '/competitions/$id/enrol'
    | '/competitions/$id/rules'
    | '/me/submissions/$submissionId'
    | '/competitions/$id/'
    | '/me/submissions/'
    | '/competitions/$id/submissions/new'
    | '/competitions/$id/tracks/$trackId'
    | '/competitions/$id/submissions/'
    | '/competitions/$id/tracks/'
    | '/dashboard/$competitionId/configure/'
    | '/dashboard/$competitionId/overview/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  MeRouteRoute: typeof MeRouteRouteWithChildren
  CompetitionsIdRouteRoute: typeof CompetitionsIdRouteRouteWithChildren
  AboutIndexRoute: typeof AboutIndexRoute
  CompetitionsIndexRoute: typeof CompetitionsIndexRoute
  LeaderboardsIndexRoute: typeof LeaderboardsIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  SignInIndexRoute: typeof SignInIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof SignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/': {
      id: '/me/'
      path: '/'
      fullPath: '/me/'
      preLoaderRoute: typeof MeIndexRouteImport
      parentRoute: typeof MeRouteRoute
    }
    '/leaderboards/': {
      id: '/leaderboards/'
      path: '/leaderboards'
      fullPath: '/leaderboards/'
      preLoaderRoute: typeof LeaderboardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/competitions/': {
      id: '/competitions/'
      path: '/competitions'
      fullPath: '/competitions/'
      preLoaderRoute: typeof CompetitionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/settings': {
      id: '/me/settings'
      path: '/settings'
      fullPath: '/me/settings'
      preLoaderRoute: typeof MeSettingsRouteImport
      parentRoute: typeof MeRouteRoute
    }
    '/me/enrolments': {
      id: '/me/enrolments'
      path: '/enrolments'
      fullPath: '/me/enrolments'
      preLoaderRoute: typeof MeEnrolmentsRouteImport
      parentRoute: typeof MeRouteRoute
    }
    '/dashboard/$competitionId': {
      id: '/dashboard/$competitionId'
      path: '/$competitionId'
      fullPath: '/dashboard/$competitionId'
      preLoaderRoute: typeof DashboardCompetitionIdRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/competitions/$id': {
      id: '/competitions/$id'
      path: '/competitions/$id'
      fullPath: '/competitions/$id'
      preLoaderRoute: typeof CompetitionsIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/submissions/': {
      id: '/me/submissions/'
      path: '/submissions'
      fullPath: '/me/submissions/'
      preLoaderRoute: typeof MeSubmissionsIndexRouteImport
      parentRoute: typeof MeRouteRoute
    }
    '/competitions/$id/': {
      id: '/competitions/$id/'
      path: '/'
      fullPath: '/competitions/$id/'
      preLoaderRoute: typeof CompetitionsIdIndexRouteImport
      parentRoute: typeof CompetitionsIdRouteRoute
    }
    '/me/submissions/$submissionId': {
      id: '/me/submissions/$submissionId'
      path: '/submissions/$submissionId'
      fullPath: '/me/submissions/$submissionId'
      preLoaderRoute: typeof MeSubmissionsSubmissionIdRouteImport
      parentRoute: typeof MeRouteRoute
    }
    '/competitions/$id/rules': {
      id: '/competitions/$id/rules'
      path: '/rules'
      fullPath: '/competitions/$id/rules'
      preLoaderRoute: typeof CompetitionsIdRulesRouteImport
      parentRoute: typeof CompetitionsIdRouteRoute
    }
    '/competitions/$id/enrol': {
      id: '/competitions/$id/enrol'
      path: '/enrol'
      fullPath: '/competitions/$id/enrol'
      preLoaderRoute: typeof CompetitionsIdEnrolRouteImport
      parentRoute: typeof CompetitionsIdRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$competitionId/overview/': {
      id: '/dashboard/$competitionId/overview/'
      path: '/overview'
      fullPath: '/dashboard/$competitionId/overview/'
      preLoaderRoute: typeof DashboardCompetitionIdOverviewIndexRouteImport
      parentRoute: typeof DashboardCompetitionIdRouteRoute
    }
    '/dashboard/$competitionId/configure/': {
      id: '/dashboard/$competitionId/configure/'
      path: '/configure'
      fullPath: '/dashboard/$competitionId/configure/'
      preLoaderRoute: typeof DashboardCompetitionIdConfigureIndexRouteImport
      parentRoute: typeof DashboardCompetitionIdRouteRoute
    }
    '/competitions/$id/tracks/': {
      id: '/competitions/$id/tracks/'
      path: '/tracks'
      fullPath: '/competitions/$id/tracks/'
      preLoaderRoute: typeof CompetitionsIdTracksIndexRouteImport
      parentRoute: typeof CompetitionsIdRouteRoute
    }
    '/competitions/$id/submissions/': {
      id: '/competitions/$id/submissions/'
      path: '/submissions'
      fullPath: '/competitions/$id/submissions/'
      preLoaderRoute: typeof CompetitionsIdSubmissionsIndexRouteImport
      parentRoute: typeof CompetitionsIdRouteRoute
    }
    '/competitions/$id/tracks/$trackId': {
      id: '/competitions/$id/tracks/$trackId'
      path: '/tracks/$trackId'
      fullPath: '/competitions/$id/tracks/$trackId'
      preLoaderRoute: typeof CompetitionsIdTracksTrackIdRouteImport
      parentRoute: typeof CompetitionsIdRouteRoute
    }
    '/competitions/$id/submissions/new': {
      id: '/competitions/$id/submissions/new'
      path: '/submissions/new'
      fullPath: '/competitions/$id/submissions/new'
      preLoaderRoute: typeof CompetitionsIdSubmissionsNewRouteImport
      parentRoute: typeof CompetitionsIdRouteRoute
    }
  }
}

interface DashboardCompetitionIdRouteRouteChildren {
  DashboardCompetitionIdConfigureIndexRoute: typeof DashboardCompetitionIdConfigureIndexRoute
  DashboardCompetitionIdOverviewIndexRoute: typeof DashboardCompetitionIdOverviewIndexRoute
}

const DashboardCompetitionIdRouteRouteChildren: DashboardCompetitionIdRouteRouteChildren =
  {
    DashboardCompetitionIdConfigureIndexRoute:
      DashboardCompetitionIdConfigureIndexRoute,
    DashboardCompetitionIdOverviewIndexRoute:
      DashboardCompetitionIdOverviewIndexRoute,
  }

const DashboardCompetitionIdRouteRouteWithChildren =
  DashboardCompetitionIdRouteRoute._addFileChildren(
    DashboardCompetitionIdRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardCompetitionIdRouteRoute: typeof DashboardCompetitionIdRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardCompetitionIdRouteRoute:
    DashboardCompetitionIdRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface MeRouteRouteChildren {
  MeEnrolmentsRoute: typeof MeEnrolmentsRoute
  MeSettingsRoute: typeof MeSettingsRoute
  MeIndexRoute: typeof MeIndexRoute
  MeSubmissionsSubmissionIdRoute: typeof MeSubmissionsSubmissionIdRoute
  MeSubmissionsIndexRoute: typeof MeSubmissionsIndexRoute
}

const MeRouteRouteChildren: MeRouteRouteChildren = {
  MeEnrolmentsRoute: MeEnrolmentsRoute,
  MeSettingsRoute: MeSettingsRoute,
  MeIndexRoute: MeIndexRoute,
  MeSubmissionsSubmissionIdRoute: MeSubmissionsSubmissionIdRoute,
  MeSubmissionsIndexRoute: MeSubmissionsIndexRoute,
}

const MeRouteRouteWithChildren =
  MeRouteRoute._addFileChildren(MeRouteRouteChildren)

interface CompetitionsIdRouteRouteChildren {
  CompetitionsIdEnrolRoute: typeof CompetitionsIdEnrolRoute
  CompetitionsIdRulesRoute: typeof CompetitionsIdRulesRoute
  CompetitionsIdIndexRoute: typeof CompetitionsIdIndexRoute
  CompetitionsIdSubmissionsNewRoute: typeof CompetitionsIdSubmissionsNewRoute
  CompetitionsIdTracksTrackIdRoute: typeof CompetitionsIdTracksTrackIdRoute
  CompetitionsIdSubmissionsIndexRoute: typeof CompetitionsIdSubmissionsIndexRoute
  CompetitionsIdTracksIndexRoute: typeof CompetitionsIdTracksIndexRoute
}

const CompetitionsIdRouteRouteChildren: CompetitionsIdRouteRouteChildren = {
  CompetitionsIdEnrolRoute: CompetitionsIdEnrolRoute,
  CompetitionsIdRulesRoute: CompetitionsIdRulesRoute,
  CompetitionsIdIndexRoute: CompetitionsIdIndexRoute,
  CompetitionsIdSubmissionsNewRoute: CompetitionsIdSubmissionsNewRoute,
  CompetitionsIdTracksTrackIdRoute: CompetitionsIdTracksTrackIdRoute,
  CompetitionsIdSubmissionsIndexRoute: CompetitionsIdSubmissionsIndexRoute,
  CompetitionsIdTracksIndexRoute: CompetitionsIdTracksIndexRoute,
}

const CompetitionsIdRouteRouteWithChildren =
  CompetitionsIdRouteRoute._addFileChildren(CompetitionsIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  MeRouteRoute: MeRouteRouteWithChildren,
  CompetitionsIdRouteRoute: CompetitionsIdRouteRouteWithChildren,
  AboutIndexRoute: AboutIndexRoute,
  CompetitionsIndexRoute: CompetitionsIndexRoute,
  LeaderboardsIndexRoute: LeaderboardsIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  SignInIndexRoute: SignInIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
