with:
  - ../../packages/noop
  - ../../packages/db/prisma
appName: GPPC
appDescription: GPPC is etc.etc.
auth:
  email:
    providerOptions: {}
    betterAuthOptions: {}
    signInParams: {}
    signOutParams: {}
    signUpParams: {}
  gitlab:
    providerOptions: {}
    betterAuthOptions: {}
    signInParams: {}
    signOutParams: {}
    signUpParams: {}
  github:
    providerOptions: {}
    betterAuthOptions: {}
    signInParams: {}
    signOutParams: {}
    signUpParams: {}
db:
  provider: postgresql
  url: postgres://postgres:postgres@localhost:5433/postgres
competitions:
  - id: "fit5037"
    with: []
    name: "FIT5047 Pacman Competition"
    tracks: []
    runner:
      with: []
    leaderboards: []
